meta_name: "Asta"
meta_title: "A melhor conexão entre profissional e cliente"
meta_description: "Conectamos os melhores talentos independentes com os melhores produtores"
meta_image: "Asta-Logo.svg"

